services:
  app:
    container_name: "${COMPOSE_PROJECT_NAME}-app"
    build:
      context: ../../
      dockerfile: .build/local/app/Dockerfile
    ports:
      - target: 8000
        published: "${APP_PORT_EXPOSE}"
        protocol: tcp
        mode: host
    volumes:
      - ../../app:/app
    env_file: .env
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
  db:
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    image: postgres:17.6
    ports:
      - target: 5432
        published: "${DB_PORT_EXPOSE}"
        protocol: tcp
        mode: host
    volumes:
      - ./database/data:/pg-data
      - ./database/dump:/dump
    environment:
      PGDATA: /pg-data
      POSTGRES_DB: ${DB__DATABASE}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB__USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP протокол
      - "15672:15672" # Web UI (management)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5  

volumes:
  rabbitmq_data:
